### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by jinwenhua** [microsoft/vscode-loader#27]
I got an error when I am trying to require nls.js in my test like "var nls = require("../../../src/nls");"
 ReferenceError: define is not defined
    at NLSLoaderPlugin (D:\vscode-loader\src\nls.js:152:5)
    at Object.<anonymous> (D:\vscode-loader\src\nls.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\vscode-loader\tests\node-specific\z-cached-data-create\_test.js:5:11)

**Comment by alexdima** [comment]
`nls` is an amd module, not a commonjs module, so it is not possible to load it using commonjs `require`.
